# Generated by scripts/build_formula.py; update with every release.
class CodexUi < Formula
  desc "Your agent. Your computer. Full control. Native desktop eyes and hands"
  homepage "https://ensomniac.github.io/codex-ui/"
  url "https://github.com/ensomniac/codex-ui/releases/download/v2.0.0/ensomniac_codex_ui-2.0.0-py3-none-any.whl", using: :nounzip
  sha256 "07293edeb5804bb491a94085b01836e50eb5c637e8cae76f8a0d2dcfce8c5a91"
  version "2.0.0"
  license "MIT"
  depends_on :macos
  depends_on macos: :ventura
  depends_on "python@3.12"
  depends_on "uv"

  resource "pyobjc-core" do
    url "https://files.pythonhosted.org/packages/86/b2/bbf7f049880ab40d110e66f25122342a1f6c98d6fe3c59bb98985503c660/pyobjc_core-12.2.2-cp312-cp312-macosx_10_13_universal2.whl", using: :nounzip
    sha256 "122e6ad302a2abf5d4d4adb0156db751600ddf2768441696cba17b31323085e7"
  end

  resource "pyobjc-framework-cocoa" do
    url "https://files.pythonhosted.org/packages/fd/2f/b67e73d8bc367e03fe7861cd9c49fff9dcfa6db83bc0630c0adcfb25b7fa/pyobjc_framework_cocoa-12.2.2-cp312-cp312-macosx_10_13_universal2.whl", using: :nounzip
    sha256 "e106f395531e67694376b0f1184612cbeea3ec8b9bf56b55ef41d026171d2a2d"
  end

  resource "pyobjc-framework-quartz" do
    url "https://files.pythonhosted.org/packages/ed/e4/8be95d2ff850f82fb55b44c63333a00a920bf8a73642e7d9c2f3638a26d2/pyobjc_framework_quartz-12.2.2-cp312-cp312-macosx_10_13_universal2.whl", using: :nounzip
    sha256 "7f668979d0c7320bf8f7ed6e030da578f93ab0f5dd619b295ec735cd8d5faa34"
  end

  resource "pyobjc-framework-applicationservices" do
    url "https://files.pythonhosted.org/packages/00/ed/9d85751400f1cd23d71c824a57352ec4d216a8728255dc00c032c431d3ad/pyobjc_framework_applicationservices-12.2.2-cp312-cp312-macosx_10_13_universal2.whl", using: :nounzip
    sha256 "5506bd6b5268a97fcb79b5b021f6cbbaaf5cdff3ec87094d8870268d8cf096ed"
  end

  resource "pyobjc-framework-coretext" do
    url "https://files.pythonhosted.org/packages/1c/88/e85a9268285fc0c28284dbdc869a27f5d3f2e436d2838221a6704b4f8eee/pyobjc_framework_coretext-12.2.2-cp312-cp312-macosx_10_13_universal2.whl", using: :nounzip
    sha256 "a69611de569d92776e6391ca25492a5bbb4a05ba744006349e377a4fc5f7c8a5"
  end

  def install
    system Formula["uv"].opt_bin/"uv", "venv", "--python", Formula["python@3.12"].opt_bin/"python3.12", libexec
    wheel_dir = buildpath/"wheels"
    wheel_dir.mkpath
    resources.each do |r|
      r.stage { wheel_dir.install Dir["*.whl"] }
    end
    wheel_dir.install buildpath/"ensomniac_codex_ui-2.0.0-py3-none-any.whl"
    system Formula["uv"].opt_bin/"uv", "pip", "install", "--offline", "--no-deps", "--python", libexec/"bin/python", *Dir[wheel_dir/"*.whl"]
    (bin/"codex-ui").write <<~SH
      #!/bin/sh
      export CODEX_UI_MANAGER=homebrew
      exec "#{libexec}/bin/codex-ui" "$@"
    SH
  end

  test do
    assert_match "codex-ui 2.0.0", shell_output("#{bin}/codex-ui --version")
    assert_match '"desktop_supported": true', shell_output("#{bin}/codex-ui capabilities")
  end
end
