"""Generate a self-contained Homebrew formula from the built release wheel."""
import hashlib
import importlib.metadata
import json
from pathlib import Path
import urllib.request

from codex_ui import __version__

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    wheel = ROOT / f"dist/ensomniac_codex_ui-{__version__}-py3-none-any.whl"
    resources = []
    for package in ("pyobjc-core", "pyobjc-framework-Cocoa", "pyobjc-framework-Quartz",
                    "pyobjc-framework-ApplicationServices", "pyobjc-framework-CoreText"):
        version = importlib.metadata.version(package)
        with urllib.request.urlopen(f"https://pypi.org/pypi/{package}/{version}/json", timeout=30) as response:
            data = json.load(response)
        asset = next(row for row in data["urls"] if "cp312-cp312" in row["filename"] and "universal2.whl" in row["filename"])
        resources.append(f'''  resource "{package.lower()}" do
    url "{asset['url']}", using: :nounzip
    sha256 "{asset['digests']['sha256']}"
  end
''')
    text = f'''# Generated by scripts/build_formula.py; update with every release.
class CodexUi < Formula
  desc "Your agent. Your computer. Full control. Native desktop eyes and hands"
  homepage "https://ensomniac.github.io/codex-ui/"
  url "https://github.com/ensomniac/codex-ui/releases/download/v{__version__}/{wheel.name}", using: :nounzip
  sha256 "{hashlib.sha256(wheel.read_bytes()).hexdigest()}"
  version "{__version__}"
  license "MIT"
  depends_on :macos
  depends_on macos: :ventura
  depends_on "python@3.12"
  depends_on "uv"

{chr(10).join(resources)}
  def install
    system Formula["uv"].opt_bin/"uv", "venv", "--python", Formula["python@3.12"].opt_bin/"python3.12", libexec
    wheel_dir = buildpath/"wheels"
    wheel_dir.mkpath
    resources.each do |r|
      r.stage {{ wheel_dir.install Dir["*.whl"] }}
    end
    wheel_dir.install buildpath/"{wheel.name}"
    system Formula["uv"].opt_bin/"uv", "pip", "install", "--offline", "--no-deps", "--python", libexec/"bin/python", *Dir[wheel_dir/"*.whl"]
    (bin/"codex-ui").write <<~SH
      #!/bin/sh
      export CODEX_UI_MANAGER=homebrew
      exec "#{{libexec}}/bin/codex-ui" "$@"
    SH
  end

  test do
    assert_match "codex-ui {__version__}", shell_output("#{{bin}}/codex-ui --version")
    assert_match '"desktop_supported": true', shell_output("#{{bin}}/codex-ui capabilities")
  end
end
'''
    target = ROOT / "Formula/codex-ui.rb"
    target.parent.mkdir(exist_ok=True)
    target.write_text(text)
    print(f"Generated {target.relative_to(ROOT)} with offline, hash-pinned universal2 dependencies")


if __name__ == "__main__":
    main()
